
sudo: required

services:
  - docker

before_install: 
  - docker build -t samip001/frontend-dockerapp -f Dockerfile.dev .

script: 
  - docker run samip001/frontend-dockerapp npm run test -- --coverage --watchAll=false