
sudo: required

services:
  - docker

before_install: 
  - docker build -t samip001/frontend-dockerapp -f Dockerfile.dev .

script: 
  - docker run samip001/frontend-dockerapp npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerstartupenv"
  env: "dockerstartupenv"
  bucket_name: "elasticbeanstalk-us-east-1-531265995453"
  bucket_path: "dockerstartupenv"
  on:
    branch: main
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"